services:
  php:
    user: '${USER_ID}:${GROUP_ID}'
    build: ./docker/php
    volumes:
      - .:/var/www:delegated
    working_dir: /var/www
    depends_on:
      - database
    networks:
      - app_network

  nginx:
    build: ./docker/nginx
    ports:
     - "8080:80"
    volumes:
      - ./public:/var/www/public:delegated
    depends_on:
     - php
    networks:
      - app_network

  database:
    image: mysql:8.2.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
    volumes:
      - database_data:/var/lib/mysql:rw
      - ./var/mysql:/var/www/var
    networks:
      - app_network

  phpmyadmin:
    image: phpmyadmin:5.2.1
    depends_on:
      - database
    restart: always
    environment:
      PMA_ARBITRARY: 1
    ports:
      - "8082:80"
    networks:
      - app_network

  mailer:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - app_network

networks:
  app_network:

volumes:
  database_data:
